---
name: Mega Lint Code Base

on:
    push:
    pull_request:
        branches: [master, main]

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    mega-lint:
        name: Mega Lint Code Base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Check GITHUB_WORKSPACE var
              run: echo "$GITHUB_WORKSPACE"

            - name: Check the current working directory
              run: pwd && ls -asl

            - name: Put .perlcriticrc in the home folder
              run: cp .github/linters/.perlcriticrc "$HOME"

            - name: Put .perlcriticrc in the project root folder
              run: cp .github/linters/.perlcriticrc ./

            - name: Mega Lint Code Base
              uses: megalinter/megalinter@v5
              env:
                  CSS_FILE_NAME: ./.github/linters/.stylelintrc.json
                  DEFAULT_BRANCH: main
                  DISABLE_LINTERS: PYTHON_FLAKE8,SPELL_CSPELL
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  JAVASCRIPT_DEFAULT_STYLE: prettier
                  LINTER_RULES_PATH: /
                  MARKDOWN_CONFIG_FILE: ./.github/linters/.markdown-lint.yml
                  NATURAL_LANGUAGE_CONFIG_FILE: ./.github/linters/.textlintrc.json
                  PERL_PERLCRITIC: ./.github/linters/.perlcriticrc
                  PYTHON_BLACK_CONFIG_FILE: ./.github/linters/.python-black
                  PYTHON_ISORT_CONFIG_FILE: ./.github/linters/.isort.cfg
                  VALIDATE_YAML: false

            # Upload MegaLinter artifacts
            - name: Archive production artifacts
              if: ${{ success() }} || ${{ failure() }}
              uses: actions/upload-artifact@v2
              with:
                  name: MegaLinter reports
                  path: |
                      report
                      mega-linter.log
