---
name: Unit tests

on: push

jobs:
    test:
        name: Unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Check Perl version
              run: perl --version

            - name: Unit tests
              run: perl wi.t
